server:
  port: 8081
spring:
  application:
    name: mizore-order
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mizore_order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: mizore
    password: mizore

  data:
    redis:
      host: localhost
      port: 6379
      password: mizore
      database: 1

